package com.clientsideeye.burp.core;

public enum FindingType {
    PASSWORD_VALUE_IN_DOM,
    HIDDEN_OR_DISABLED_CONTROL,
    ROLE_PERMISSION_HINT,
    INLINE_SCRIPT_SECRETISH,
    DEVTOOLS_BLOCKING,
    JAVASCRIPT_ENDPOINT_REFERENCE,
    DOM_XSS_SINK,
    POSTMESSAGE_HANDLER,
    STORAGE_TOKEN,
    SOURCE_MAP_DISCLOSURE,
    RUNTIME_NETWORK_REFERENCE
}
